spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/culinary_craft_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      default-schema: public
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      enabled: false

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  constants:
    companyName: "Culinary Craft"

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

apiVersion: "/api/v1"

admin:
  password: ${ADMIN_PASSWORD}