spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/culinary_craft_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      default-schema: public
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          # Google login
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
             - email
             - profile
          # Facebook login
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
          # GitHub login
#          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG