name: culinary_craft_wireframe
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 6.1.0
  provider: 6.1.2
  smooth_page_indicator: 1.1.0
  flutter_keyboard_visibility: 6.0.0
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/